### ISSUE TITLE
 Can't see the photo of Architecture and Comparison Example

### ISSUE THREAD

**Issue by JeffYaCheng** [xiazhaoqiang/IENet-HeartRateEst#1]
- Fist,  I just saw the link in the readme.
![image](https://github.com/xiazhaoqiang/IENet-HeartRateEst/assets/100260113/02934007-4b18-42da-819d-6f57ba189194)
- Then, clip the link. Result is nothing.
![image](https://github.com/xiazhaoqiang/IENet-HeartRateEst/assets/100260113/cc7d5f1d-271b-46aa-b2c6-85bf1ac6a465)
- Can author deal this problem. Thank you very much.

**Comment by xiazhaoqiang** [comment]
Thanks for your reminding. I have fixed this issue by using the relative link. If you still cannot find them, please access the results folder.
